### ISSUE TITLE
on_click appbar route

### ISSUE THREAD

**Issue by SofExp** [fasilwdr/Flet-Model#1]
Transition from appbar does not work, TypeError: 'str' object is not callable.
ElevatedButton work.
code:

```
import flet as ft
from flet_model import Model, Router


class HomePage(Model):
    route = 'home'

    controls = [
        ft.Text('HomePage HERE', size=30),
        ft.ElevatedButton('auth_go', on_click='auth_to'),
        ft.AppBar(
            title=ft.Text("Orders", color='#FFFFFF',),
            center_title=True,
            adaptive=True,
            bgcolor="#012E57",
            actions=[
                ft.IconButton(icon=ft.icons.LIST_ALT,
                                icon_color='#FFFFFF',
                                padding=ft.padding.only(left=30, right=30),
                                on_click= 'auth_to',
                                ),
            ],
        ),
    ]
    
    def auth_to(self, e):
        self.page.go("auth")
```

**Comment by fasilwdr** [comment]
```python
import flet as ft
from flet_model import Model, Router


class HomePage(Model):
    route = 'home'

    controls = [
        ft.Text('HomePage HERE', size=30),
        ft.ElevatedButton('auth_go', on_click='auth_to'),
        ft.AppBar(
            title=ft.Text("Orders", color='#FFFFFF', ),
            center_title=True,
            adaptive=True,
            bgcolor="#012E57",
            actions=[
                ft.IconButton(icon=ft.icons.LIST_ALT,
                              icon_color='#FFFFFF',
                              padding=ft.padding.only(left=30, right=30),
                              on_click='auth_to',
                              ),
            ],
        ),
    ]

    def auth_to(self, e):
        print("Triggered...")
        self.page.go("auth")

def main(page: ft.Page):
    page.title = "Title"
    page.theme_mode = "light"
    # Initialize router with route mappings
    Router(
        {'home': HomePage(page)},
    )

    page.go(page.route)


ft.app(target=main)
```


it Works !.
Make sure "auth" is added into Router

**Comment by SofExp** [comment]
Copied your code.
Does not work when clicking on IconButton from AppBar.
Error:

Future exception was never retrieved
future: <Future finished exception=TypeError("'str' object is not callable")>
Traceback (most recent call last):
  File "C:\Program Files\Python312\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\Desktop\Orders\.venv\Lib\site-packages\flet_core\page.py", line 944, in wrapper
    handler(*args)
TypeError: 'str' object is not callable

**Comment by fasilwdr** [comment]
@SofExp Please share your complete code

**Comment by SofExp** [comment]
> @SofExp Please share your complete code


cod:
```
import flet as ft
from flet_model import Model, Router


class HomePage(Model):
    route = 'home'

    controls = [
        ft.Text('HomePage HERE', size=30),
        ft.ElevatedButton('auth_go', on_click='auth_to'),
        ft.AppBar(
            title=ft.Text("Orders", color='#FFFFFF', ),
            center_title=True,
            adaptive=True,
            bgcolor="#012E57",
            actions=[
                ft.IconButton(icon=ft.icons.LIST_ALT,
                              icon_color='#FFFFFF',
                              padding=ft.padding.only(left=30, right=30),
                              on_click='auth_to',
                              ),
            ],
        ),
    ]

    def auth_to(self, e):
        print("Triggered...")
        self.page.go("auth")

class AuthenticationPage (Model):
    route = 'auth'
    
    def add_new_el():
        return (
                ft.Text('AuthenticationPage def', size=30, color = "#71a3c1")
            )
    
    controls = [
        ft.Text('AuthenticationPage here', size=30),
        ft.ElevatedButton('home_go', on_click='home_to'),
        add_new_el(),
    ]
    
    def home_to(self, e):
        self.page.go("home")

def main(page: ft.Page):
    page.title = "Title"
    page.theme_mode = "light"
    # Initialize router with route mappings
    Router(
        {'home': HomePage(page)},
        {'auth': AuthenticationPage(page)},
    )

    page.go(page.route)


ft.app(target=main)
```

**Comment by fasilwdr** [comment]
I didn’t quite understand your concern. The code seems to be working perfectly.

![Recording 2024-12-03 094624](https://github.com/user-attachments/assets/5e13e75b-0a23-456f-ac6c-2da5c015dc98)

**Comment by SofExp** [comment]
Worked after the update, thanks.
Have you tested this library on Android?

**Comment by fasilwdr** [comment]
yeah, it works
